### ISSUE TITLE
Not Implement Firebase Cloud Messaging API (V1) 

### ISSUE THREAD

**Issue by cdzhoubin** [mistrypragnesh40/PushNotificationDemoMAUI#1]
Not Implement Firebase Cloud Messaging API (V1)

**Comment by evk200** [comment]
me too..

**Comment by rajeshsws** [comment]
all working fine but notification is not coming.  response code status is also ok

**Comment by rajeshsws** [comment]
Its working after adding pendingintent Immutable

            var pendingIntent = PendingIntent.GetActivity(this,
                 MainActivity.notificationid, intent, PendingIntentFlags.Immutable);

**Comment by mistrypragnesh40** [comment]
Added push notification for iOS.
