### ISSUE TITLE
Permission Request Issue

### ISSUE THREAD

**Issue by canperk** [mistrypragnesh40/PushNotificationDemoMAUI#4]
When trying to force user to allow notifications like below as you implemented at MainActivity.cs

`ActivityCompat.RequestPermissions(this, new string[] { Android.Manifest.Permission.PostNotifications }, 1);`

It is not asking if user allows notifications or not. Did you make anything special?

**Comment by mistrypragnesh40** [comment]
No just above code, and 
this permission in manifest file.

`<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>`

**Comment by canperk** [comment]
If you mean this

`<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>`

tehn I have it. Did you get the request mesaage box from Android? On your video IOS asks but not Android

**Comment by mistrypragnesh40** [comment]
Yes, I get that permission box. but tested in android emulator API- 33.

**Comment by canperk** [comment]
What about versions below 33? Do you have any idea?

**Comment by canperk** [comment]
It is allowed by default below API 33. Thus I am closing this
